global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus-job'
    static_configs:
      - targets: ['localhost:8082']
        labels:
          application: cep-api-consumer
    metrics_path: /actuator/prometheus